---
- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  when: 
  - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  - ansible_os_family == 'Debian' and ansible_distribution_major_version > '16'

- name: restart elasticsearch
  systemd: name=elasticsearch state=restarted
  when:
  - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  - ansible_os_family == 'Debian' and ansible_distribution_major_version == '16'

- name: apt update
  command: apt-get update
