---
- name: "start {{role_name}}"
  service: name={{daemon_name}} state=started

- name: "restart {{role_name}}"
  service: name={{daemon_name}} state=restarted

- name: "reload {{role_name}}"
  service: name={{daemon_name}} state=reloaded

- name: "stop {{role_name}}"
  service: name={{daemon_name}} state=stop
