---
- apt: name=apache2 state="latest"
- template:
    src: httpd.conf.{{ansible_os_family}}.{{ansible_distribution_major_version}}.j2
    dest: /etc/apache2/httpd.conf
    owner: 0
    group: 0
    mode: 0644
  notify:
    - restart apache
