---
- name: Install apache
  yum: name=httpd state="latest"

- name: Set httpd.conf
  template:
    src: httpd.conf.{{ansible_os_family}}.{{ansible_distribution_major_version}}.j2
    dest: "{{file_httpd_conf}}"
    owner: 0
    group: 0
    mode: 0644
  notify: "restart {{role_name}}"

- name: Replace welcome.conf to emptyfile
  template:
    src: emptyfile
    dest: "{{path_confd}}welcome.conf"
    owner: 0
    group: 0
    mode: 0644
  notify: "restart {{role_name}}"
