---
- name: restart apache
  service: name=httpd state=restarted
  when: 
  - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  - ansible_os_family == 'Debian' and ansible_distribution_major_version > '16'

- name: restart apache
  systemd: name=httpd state=restarted
  when:
  - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  - ansible_os_family == 'Debian' and ansible_distribution_major_version == '16'
